services:
  postgres:
    image: postgres:15
    container_name: gmm_postgres
    restart: always
    environment:
      POSTGRES_USER: gmm_user
      POSTGRES_PASSWORD: gmm_pass
      POSTGRES_DB: gmm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gmm_pgadmin
    restart: always
    ports:
      - "8080:80"  # Web access
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_pass
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
